[tool.ruff]
select = ["ALL"]


ignore = [
"ANN201", # Missing return type annotation for public function `initialize`
"ANN101", # Missing type annotation for `self` in method
]

# Show potential fixes
show-fixes = true

# Compatible for which version
target-version = "py38"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}